version: '3'

services:
  server:
    build: .
    container_name: "server"
    ports:
      - 3000:3000
    links:
      - mongo
    depends_on:
      - mongo
    env_file:
      - ./docker/env/production.env

  nginx:
    image: nginx:latest
    container_name: "nginx"
    ports:
      - "80:80"
    depends_on:
      - server
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:cached

  mongo:
    image: mongo
    container_name: "mongo"
    command:
      - mongod
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  mongo-data:
    image: busybox

volumes:
  mongo-data:

